version: "3.9"

services:
  # Define the web application service
  web:
    image: node:20-alpine
    container_name: my_web_app
    ports:
      - "3000:3000" # Host:Container
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  # Define the database service (MongoDB)
  db:
    image: mongo:6
    container_name: my_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

# Define named volumes
volumes:
  mongo_data:
